/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package L_Presentation;

import L_Business.B_User;
import L_Entity.E_User;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jean
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Login x = 51; y = 275;
     */
    P_PlaceHolder JtxtUserName;
    P_PlaceHolder JtxtPassword;

    public FrmLogin() {
        this.initComponents();
        this.MyInitComponents();
    }

    private void MyInitComponents() {
        this.setLocationRelativeTo(null);
        this.InitJtxtUserName();
        this.InitJtxtPassword();
        this.JtxtUserName.addFocusListener(new java.awt.event.FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
            }

            @Override
            public void focusLost(FocusEvent e) {
            }
        });
    }

    private void InitJtxtUserName() {
        this.JtxtUserName = new P_PlaceHolder();
        this.JtxtUserName.setLocation(50, 270);
        this.JtxtUserName.setPlaceHolderText("Usuario");
        this.JtxtUserName.setSize(new Dimension(200, 35));
        this.JtxtUserName.setPhColor(new Color(72, 117, 210));
        this.JtxtUserName.setFont(new Font("SansSerif", Font.PLAIN, 12));
        this.JtxtUserName.setName("jtxtUserName");
        this.JtxtUserName.setToolTipText("Usuario");
        this.add(this.JtxtUserName);
    }

    private void InitJtxtPassword() {
        this.JtxtPassword = new P_PlaceHolder();
        this.JtxtPassword.setLocation(50, 310);
        this.JtxtPassword.setPlaceHolderText("Contraseña");
        this.JtxtPassword.setSize(new Dimension(200, 35));
        this.JtxtPassword.setPhColor(new Color(72, 117, 210));
        this.JtxtPassword.setFont(new Font("SansSerif", Font.PLAIN, 12));
        this.JtxtPassword.setName("JtxtPassword");
        this.JtxtPassword.setToolTipText("Contraseña");
        this.add(this.JtxtPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setAutoRequestFocus(false);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(300, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 450));

        jbtnLogin.setText("Entrar");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        int resp = 0;
        B_User B_User = new B_User();
        E_User E_User = new E_User();
        E_User.setUserName(this.JtxtUserName.getText());
        E_User.setUserPassword(this.JtxtPassword.getText());
        try {
            resp = B_User.LoginUser(E_User);
            if (resp > 0) {
                FrmMain frmMain = new FrmMain();
                frmMain.setVisible(true);
                this.setVisible(false);
            }
        } catch (Exception e) {
        } finally {
            System.out.println(resp);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    // End of variables declaration//GEN-END:variables
}
